apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kd4-deployment-autoscaler
  namespace: default  # replace this with your actual namespace if it's not "default"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kd4-deployment
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50
