apiVersion: apps/v1
kind: Deployment
metadata:
  name: myhello-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myhello
  template:
    metadata:
      labels:
        app: myhello
    spec:
      containers:
      - name: myhello
        image: arunsundaramco70/myhello
        ports:
        - containerPort: 8888
