apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-app
spec:
  containers:
    - name: my-container
      image: arunsundaramco70/hello
      ports:
        - containerPort: 8001
          name: http-web-svc
      env:
        - name: GREET_PREFIX
          valueFrom:
            configMapKeyRef:
              name: my-config-map
              key: greet_prefix
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app
  type: NodePort
  ports:
  - name: front-end-port
    protocol: TCP
    port: 8001
    targetPort: http-web-svc
    nodePort: 30088
