apiVersion: v1
kind: Service
metadata:
  name: upper-service
spec:
  selector:
    app: upper-app
  type: LoadBalancer
  ports:
  - name: front-end-port
    protocol: TCP
    port: 8089
    targetPort: http-web-svc
    nodePort: 30089
