apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-world-cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello-world
            image: busybox
            args:
            - /bin/bash
            - -c
            - "echo 'Hello World2 $(date)' >> /data/greetings.txt"
            volumeMounts:
            - name: data-volume
              mountPath: /data
          volumes:
          - name: data-volume
            hostPath:
              path: /home/asundaram/apps/docker-training/kd12-cronjob-minikube-volume-mount/data
              type: DirectoryOrCreate
          restartPolicy: OnFailure
