apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-world-cronjob
spec: # cron specification
  schedule: "* * * * *"
  jobTemplate: # pod specification
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: hello-world
            image: alpine
            args:
            - /bin/sh
            - -c
            - badCommand && mkdir /data; echo 'Hello World2 $(date)' >> /data/greetings.txt; sleep 360
