apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test-container
    image: busybox
    args:
      - /bin/sh
      - -c
      - "while true; do sleep 3600; done"
    volumeMounts:
    - name: data-volume
      mountPath: /data
  volumes:
  - name: data-volume
    hostPath:
      path: /home/asundaram/apps/docker-training/kd12-cronjob-minikube-volume-mount/data
      type: Directory
