apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: my-pod
  ports:
    - protocol: TCP
      port: 8005 # the port we expose to the end-user
      targetPort: 8001 # container port that k8s will forward the request to
  sessionAffinity: None
